ALTER TABLE dependent_medicals ADD action_on VARCHAR(255) DEFAULT NULL;
ALTER TABLE dependent_schools ADD action_on VARCHAR(255) DEFAULT NULL;
ALTER TABLE estates ADD action_on VARCHAR(255) DEFAULT NULL;
ALTER TABLE members ADD action_on VARCHAR(255) DEFAULT NULL;
ALTER TABLE pets ADD action_on VARCHAR(255) DEFAULT NULL;
ALTER TABLE profiles ADD action_on VARCHAR(255) DEFAULT NULL;
ALTER TABLE sites ADD action_on VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD action_on VARCHAR(255) DEFAULT NULL;



